import Head from 'next/head';
import Header from '../components/Header';
import styled from "styled-components";
import { useAuthState } from 'react-firebase-hooks/auth';
import { auth } from '../firebase';
import Feed from '../components/Feed';

export default function Home() {

  const [user] = useAuthState(auth);

  return (
    <Container>
      <Head>
        <title>lnzgram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://naukova-zmina.org.ua/wp-content/themes/ABVV_LNZ/img/logo.png" />
      </Head>
      <Header />
      <Feed />
    </Container>
  )
}

const Container = styled.div`
    background-color: rgb(249, 250, 251);
    height: 100vh;
    overflow-x: hidden;
`;
